[workspace]
resolver = "3"
members = ["hamr", "hamr-cli"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
clap = { version = "4" }
strum = { version = "0.28", default-features = false, features = ["derive"] }
thiserror = { version = "2", default-features = false }
