[package]
name = "hamr"
description = "WIP: implementation of @p2r3's ha.mr link compression algorithm in Rust"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["std"]
std = ["dep:clap"]
